baseURL = "https://xodbs1021.github.io/"
languageCode = "ko-kr"
timeZone = "Asia/Seoul"
title = "태형이 따라잡기"
theme = "PaperMod"

[params]
  showFullContent = false
  showReadingTime = false
  showPostsOnHomePage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
  name = "Tech Blurting"
  url = "/categories/tech-blurting"
  weight = 1

[[menus.main]]
  name = "Open Source Analysis"
  url = "/categories/open-source-analysis"
  weight = 2

[[menus.main]]
  name = "Coding Test"
  url = "/categories/coding-test"
  weight = 3

[[menus.main]]
  name = "0 to 1"
  url = "/categories/0-to-1"
  weight = 4

[[menus.main]]
  name = "Book Review"
  url = "/categories/book-review"
  weight = 5
